### ISSUE TITLE
Received status code 403 from server: Forbidden

### ISSUE THREAD

**Issue by sulaukad** [spring-gradle-plugins/propdeps-plugin#12]
`      > Could not resolve io.spring.gradle:propdeps-plugin:0.0.10.RELEASE.
         > Could not get resource 'http://repo.spring.io/plugins-release/io/spring/gradle/propdeps-plugin/0.0.10.RELEASE/propdeps-plugin-0.0.10.RELEASE.pom'.
            > Could not GET 'http://repo.spring.io/plugins-release/io/spring/gradle/propdeps-plugin/0.0.10.RELEASE/propdeps-plugin-0.0.10.RELEASE.pom'. Received status code 403 from server: Forbidden
      > Could not resolve io.spring.gradle:propdeps-plugin:0.0.10.RELEASE.
         > Could not get resource 'http://repo.spring.io/milestone/io/spring/gradle/propdeps-plugin/0.0.10.RELEASE/propdeps-plugin-0.0.10.RELEASE.pom'.
            > Could not GET 'http://repo.spring.io/milestone/io/spring/gradle/propdeps-plugin/0.0.10.RELEASE/propdeps-plugin-0.0.10.RELEASE.pom'. Received status code 403 from server: Forbidden`
Any solution to this?

**Comment by bclozel** [comment]
Http is forbidden now on repo.spring.io
See https://spring.io/blog/2019/09/16/goodbye-http-repo-spring-use-https
