### ISSUE TITLE
Missing http to https redirect 403 Fordibben

### ISSUE THREAD

**Issue by nachozullo** [spring-gradle-plugins/propdeps-plugin#13]
![Captura de pantalla de 2020-01-16 10-16-34](https://user-images.githubusercontent.com/28366930/72531554-7635d500-3850-11ea-86c5-f442815ac0e1.png)

I have to change the buildscript:

`repositories {
        ...
        maven { url "https://repo.spring.io/plugins-release" }
    }
`
And then works fine.

**Comment by denDAY04** [comment]
Can confirm this is an issue, and it was a bit annoying to deal with due to the misleading 403 error.

**Comment by bclozel** [comment]
It's by design, see: https://spring.io/blog/2019/06/10/announcing-nohttp
