### ISSUE TITLE
0.0.8 version is not published yet, although released

### ISSUE THREAD

**Issue by n0mer** [spring-gradle-plugins/propdeps-plugin#3]
http://repo.spring.io/plugins-release/org/springframework/build/gradle/propdeps-plugin/

**Comment by rwinch** [comment]
Thanks for the report and sorry for the confusion...

It moved to a new group id. For updated config see https://github.com/spring-gradle-plugins/propdeps-plugin#configuration The artifact is at http://repo.spring.io/plugins-release/io/spring/gradle/propdeps-plugin/
