### ISSUE TITLE
spring boot configuration annotation processor not found in classpath

### ISSUE THREAD

**Issue by JayvinPan** [spring-gradle-plugins/propdeps-plugin#4]
I created a spring boot project with gradle. When I use @ConfigurationProperties, it occured the problem like the title described. Then I add propdeps-plugin at build file, but it doesn't work. Finally, I rewrite the "optional" to "compile", it is working.
![image](https://user-images.githubusercontent.com/26504333/28303399-917b0a56-6bc5-11e7-8902-49c874cef31a.png)
It is interesting that I use the same way to solve a same problem at a gradle project with spring boot, it doesn't work again.

**Comment by bclozel** [comment]
Could you provide a project that reproduces the issue?

**Comment by JayvinPan** [comment]
https://github.com/JayvinPan/ayakashi

**Comment by bclozel** [comment]
I've just tried with a slightly modified version of your `build.gradle` file:

```groovy
buildscript {
  ext {
    springBootVersion = '1.5.4.RELEASE'
  }
  repositories {
    mavenCentral()
    maven { url 'http://repo.spring.io/plugins-release' }
  }
  dependencies {
    classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    classpath("io.spring.gradle:propdeps-plugin:0.0.9.RELEASE")
  }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'propdeps'

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8

repositories {
  mavenCentral()
}

dependencies {
  compile('org.springframework.boot:spring-boot-starter-web')
  testCompile('org.springframework.boot:spring-boot-starter-test')

  optional "org.springframework.boot:spring-boot-configuration-processor"

  //compile('org.springframework.boot:spring-boot-configuration-processor')
}

compileJava.dependsOn(processResources)
```

And the JSON metadata file is generated at the expected location `build/classes/main/META-INF/spring-configuration-metadata.json`.

Could you elaborate a bit about this issue?

**Comment by JayvinPan** [comment]
It may be some error with my IDE, thanks for your help.
